title: SemiAlgebraicTypes

author:
  name: Bernard Mourrain
  email: your-email@domain.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
    SemiAlgebraicTypes description to be detailed
# Build settings

theme: minima
